-- 0001 — baseline: the schema as it stood at v0.1.4, when migration machinery
-- (C0, D-041) landed.
--
-- Every statement is IF NOT EXISTS, and that is load-bearing rather than tidy:
-- this file has to reach two different databases and leave them identical.
--
--   * a FRESH database  — creates everything;
--   * an EXISTING pre-C0 install — a no-op, recorded as applied.
--
-- That is the whole of the baseline problem D-041 named as C0's real risk. It
-- works only because the pre-C0 `migrate()` was itself `CREATE TABLE IF NOT
-- EXISTS` and nothing else, so the two paths converge on the same schema.
--
-- Do NOT edit this file after it has shipped: sqlx checksums each migration and
-- a changed one is refused on a database that already applied it. Schema changes
-- go in a new numbered file.
--
-- Table notes that used to live on `db.rs`'s SCHEMA constant:
--
--   leases         one row per (lease_id, path) — a single lease covering N
--                  paths is N rows sharing a lease_id, which makes the per-path
--                  conflict check a trivial indexed lookup, the hot operation
--                  on lease_acquire.
--   version_index  the BLAKE3 hash cache (concept §4.2), one current entry per
--                  canonical path. Resolve matches the composite
--                  (path, mtime_ms, size) key, so a changed file is a miss even
--                  though the path row still exists — the stale-cache signal the
--                  endpoint needs (§8.1).
--   move_journal   the in-flight-move record (B3). A new table rather than
--                  columns on `journal` because, before this migration existed,
--                  additive-by-table was the only schema change that could reach
--                  an install that had already run. That constraint is now
--                  lifted; the modelling choice stands on its own merits.
BEGIN;

CREATE TABLE IF NOT EXISTS leases (
    lease_id       TEXT    NOT NULL,
    path           TEXT    NOT NULL,   -- canonical (concept §5.1); keyed per invariant 5
    principal      TEXT    NOT NULL,   -- AD principal that holds the lease
    session_id     TEXT    NOT NULL,   -- acquiring session (for lease_* audit)
    purpose        TEXT    NOT NULL,   -- LeasePurpose, serde snake_case
    granted_at_ms  INTEGER NOT NULL,
    ttl_s          INTEGER NOT NULL,
    renewed_at_ms  INTEGER NOT NULL,
    hard_expiry_ms INTEGER NOT NULL,   -- granted_at + max lifetime (concept §9)
    expiry_ms      INTEGER NOT NULL,   -- renewed_at + ttl; the heartbeat expiry
    PRIMARY KEY (lease_id, path)
);
CREATE INDEX IF NOT EXISTS idx_leases_path ON leases(path);

CREATE TABLE IF NOT EXISTS version_index (
    path          TEXT    PRIMARY KEY,  -- canonical
    version       TEXT    NOT NULL,     -- BLAKE3 hex (invariant 2)
    mtime_ms      INTEGER NOT NULL,     -- observed modification time
    size          INTEGER NOT NULL,     -- observed size in bytes
    updated_at_ms INTEGER NOT NULL      -- when coord last refreshed this entry
);

CREATE TABLE IF NOT EXISTS journal (
    path              TEXT    PRIMARY KEY,  -- canonical; at most one in-flight write per path
    lease_id          TEXT    NOT NULL,     -- the write's owning lease (liveness ⇒ live vs dangling)
    principal         TEXT    NOT NULL,
    pre_image_version TEXT    NOT NULL,     -- last known-good; points into history (blob store)
    intended_version  TEXT,                 -- NULL if crashed before hashing new content (concept §5.2)
    opened_at_ms      INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS move_journal (
    src                   TEXT    PRIMARY KEY,  -- canonical; at most one in-flight move per source
    dst                   TEXT    NOT NULL,     -- canonical; where the file is headed
    lease_id              TEXT    NOT NULL,     -- the dual {src,dst} lease (liveness ⇒ live vs dangling)
    principal             TEXT    NOT NULL,
    session_id            TEXT    NOT NULL,
    version               TEXT    NOT NULL,     -- src's CAS-verified version; what dst must hash to
    size                  INTEGER NOT NULL,
    overwrite             INTEGER NOT NULL,     -- 0/1; whether dst existed and went through CAS
    dst_pre_image_version TEXT,                 -- overwrite only: the snapshot the rename destroyed
    dst_pre_image_size    INTEGER,              -- set together with the version, or both NULL
    opened_at_ms          INTEGER NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_move_journal_dst ON move_journal(dst);

CREATE TABLE IF NOT EXISTS version_log (
    id               INTEGER PRIMARY KEY AUTOINCREMENT,  -- append order within a file
    path             TEXT    NOT NULL,   -- canonical
    timestamp_ms     INTEGER NOT NULL,
    blob_hash        TEXT    NOT NULL,   -- this version's content address = blob-store key
    writer_principal TEXT    NOT NULL,
    prev_hash        TEXT,               -- previous version in the chain; NULL for the first
    size             INTEGER NOT NULL,
    event            TEXT    NOT NULL    -- VersionEvent, serde snake_case
);
CREATE INDEX IF NOT EXISTS idx_version_log_path ON version_log(path, id);

CREATE TABLE IF NOT EXISTS audit_log (
    id             INTEGER PRIMARY KEY AUTOINCREMENT,  -- append order
    event_id       TEXT    NOT NULL UNIQUE,
    timestamp_ms   INTEGER NOT NULL,
    principal      TEXT    NOT NULL,   -- the AD principal that acted (concept §13.1)
    session_id     TEXT    NOT NULL,
    canonical_path TEXT    NOT NULL,
    kind           TEXT    NOT NULL,   -- AuditKind, serde snake_case
    from_version   TEXT,
    to_version     TEXT,
    detail         TEXT    NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_audit_path ON audit_log(canonical_path, id);
-- Covers the admin view's principal filter. The plain fleet-wide listing needs no
-- index of its own: it orders by id, which is the primary key.
CREATE INDEX IF NOT EXISTS idx_audit_principal ON audit_log(principal, id);

CREATE TABLE IF NOT EXISTS conflicts (
    conflict_id      TEXT    PRIMARY KEY,
    base_path        TEXT    NOT NULL,   -- the live file the conflict is against (canonical)
    sidecar_path     TEXT    NOT NULL,   -- F.conflict-{user}-{ts} holding the losing bytes
    losing_principal TEXT    NOT NULL,
    created_at_ms    INTEGER NOT NULL,
    state            TEXT    NOT NULL,   -- ConflictState: open | resolved
    resolution       TEXT                -- ConflictResolution snake_case; NULL while open
);
CREATE INDEX IF NOT EXISTS idx_conflicts_base ON conflicts(base_path, state);

CREATE TABLE IF NOT EXISTS session_reads (
    session_id TEXT    NOT NULL,
    path       TEXT    NOT NULL,   -- canonical
    version    TEXT    NOT NULL,   -- a version this session has read (concept §6.2)
    seen_at_ms INTEGER NOT NULL,
    PRIMARY KEY (session_id, path, version)
);

-- Operational diagnostics (E-026). Deliberately NOT the audit log: audit records
-- what a principal did and is a primary deliverable, this records why something
-- failed. Different reader, different retention; merging them makes audit
-- unreadable. Only unexpected failures land here -- a CAS conflict or an Office
-- lock is a designed outcome and surfaces as conflict/lease status instead.
--
-- Grouped by (code, path): the failure that matters is usually the one repeating,
-- and one looping agent would otherwise bury everything else under identical rows.
CREATE TABLE IF NOT EXISTS diagnostics (
    id            TEXT    PRIMARY KEY,
    code          TEXT    NOT NULL,   -- stable machine code, from the ChaprError variant
    path          TEXT,               -- canonical; NULL for endpoint-wide problems
    title         TEXT    NOT NULL,
    severity      TEXT    NOT NULL,   -- Severity: error | warning
    detail        TEXT    NOT NULL,
    remedy        TEXT    NOT NULL,   -- what fixes it; required, not decoration
    facts_json    TEXT    NOT NULL,   -- free key/value context, so a new fact needs no migration
    state         TEXT    NOT NULL,   -- DiagnosticState: open | acknowledged | resolved
    first_seen_ms INTEGER NOT NULL,
    last_seen_ms  INTEGER NOT NULL,
    count         INTEGER NOT NULL
);
-- The grouping key. A unique index cannot span a NULL path in SQLite, so the key
-- folds a missing path to the empty string; the module maps it back to NULL.
CREATE UNIQUE INDEX IF NOT EXISTS idx_diagnostics_group
    ON diagnostics(code, IFNULL(path, ''));
CREATE INDEX IF NOT EXISTS idx_diagnostics_recent ON diagnostics(state, last_seen_ms);

-- Individual sightings within a group. Bounded per group -- the group count is the
-- real history. principal/host are what separate one misconfigured laptop from a
-- fault hitting everybody.
CREATE TABLE IF NOT EXISTS diagnostic_occurrences (
    group_id  TEXT    NOT NULL REFERENCES diagnostics(id) ON DELETE CASCADE,
    at_ms     INTEGER NOT NULL,
    principal TEXT    NOT NULL,
    host      TEXT
);
CREATE INDEX IF NOT EXISTS idx_diag_occ_group
    ON diagnostic_occurrences(group_id, at_ms);

-- The ledger row is part of this transaction on purpose: schema and record
-- commit together, so a database can never be migrated-but-unrecorded (which
-- would re-run this on every start) nor recorded-but-unmigrated.
INSERT INTO schema_migrations (version, name, applied_at_ms)
VALUES (1, 'baseline', CAST(strftime('%s', 'now') AS INTEGER) * 1000);

COMMIT;
